language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t saggitarie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saggitarie/react-test npm test

after_success:
  - docker build -t saggitarie/multi-client2 ./client
  - docker build -t saggitarie/multi-nginx2 ./nginx
  - docker build -t saggitarie/multi-server2 ./server
  - docker build -t saggitarie/multi-worker2 ./worker

  #Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  # Take those images and push them to docker hub
  - docker push saggitarie/multi-client2
  - docker push saggitarie/multi-nginx2
  - docker push saggitarie/multi-server2
  - docker push saggitarie/multi-worker2
